name: Bug Form
description: File a bug report
labels: ["bug"]
projects: ["fermi-ad/13"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Also, tell us what you expect to happen.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: Tell us what you see!
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: checkboxes
    id: system
    attributes:
      label: system
      description: What system is impacted by this bug?
      options:
        - label: Console
        - label: Java
        - label: Web
        - label: Synoptic
        - label: Front End
        - label: Central Service
    validations:
      required: true

